timeZone: Europe/Paris

paginate: 50
summaryLength: 10

defaultContentLanguage: en
defaultContentLanguageInSubdir: false

services:
  googleAnalytics: null
  disqus: null

permalinks:
  page:
    pages: /:slugorfilename/

module:
  mounts:
    - source: assets
      target: assets

build:
  noJSConfigInAssets: false
  useResourceCacheWhen: fallback
  buildStats:
    enable: true
  cachebusters:
    - source: assets/.*\.(js|ts|jsx|tsx)
      target: js
    - source: assets/.*\.(css|scss|sass)
      target: css
    - source: data/.*\.(.*)$
      target: css
    - source: assets/.*\.(.*)$
      target: $1

params:
  plugins:
    css:
      - link: plugins/swiper/swiper-bundle.css
        lazy: true
      - link: plugins/glightbox/glightbox.css
        lazy: true
      - link: plugins/font-awesome/v6/brands.css
        lazy: true
      - link: plugins/font-awesome/v6/solid.css
        lazy: true
      - link: plugins/font-awesome/v6/icons.css
        lazy: true
    js:
      - link: js/search.js
        lazy: false
      - link: plugins/swiper/swiper-bundle.js
        lazy: false
      - link: plugins/cookie.js
        lazy: false
      - link: plugins/glightbox/glightbox.js
        lazy: true
      - link: js/gallery-slider.js
        lazy: true
      - link: js/accordion.js
        lazy: true
      - link: js/tab.js
        lazy: true
      - link: js/modal.js
        lazy: true
      - link: plugins/youtube-lite.js
        lazy: true
