main:
  - name: Home
    pageRef: /
    weight: 1
  - name: Workflows
    pageRef: /workflows
    weight: 2
  - name: DevOps
    pageRef: /categories/devops/
    parent: Workflows
  - name: Samples
    pageRef: /categories/sample/
    parent: Workflows
  - name: Security
    pageRef: /categories/security/
    parent: Workflows
  - name: Support
    pageRef: /categories/support/
    parent: Workflows
  
footer: []
